#TODO - Replace your.domain.com in ingress.yaml with your actual domain.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deliverxy-ingress
  namespace: deliverxy
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: your.domain.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: deliverxy-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deliverxy-frontend-admin
                port:
                  number: 80
