import http from 'k6/http';
import { check, sleep } from 'k6';
import { Trend, Rate } from 'k6/metrics';

export const BASE_URL = __ENV.BASE_URL || 'http://localhost:8080';
export const AUTH_ENABLED = (__ENV.AUTH_ENABLED || 'true') === 'true';
export const REGISTER_TEST_USER = (__ENV.REGISTER_TEST_USER || 'true') === 'true';
export const TEST_USER_PASSWORD = __ENV.TEST_USER_PASSWORD || 'Password123!';
export const TEST_USER_EMAIL = __ENV.TEST_USER_EMAIL || `perf-${Date.now()}@deliverxy.test`;
export const TEST_USER_IDENTIFIER = __ENV.TEST_USER_IDENTIFIER || TEST_USER_EMAIL;

export const apiLatency = new Trend('deliverxy_api_latency_ms');
export const apiErrors = new Rate('deliverxy_api_errors');

export function defaultHeaders(token = null) {
  const headers = {
    'Content-Type': 'application/json',
    Accept: 'application/json',
  };

  if (token) {
    headers.Authorization = `Bearer ${token}`;
  }

  return { headers };
}

export function randomPhone() {
  return `+3897${Math.floor(1000000 + Math.random() * 8999999)}`;
}

export function buildRegisterPayload(role = 'CLIENT') {
  const suffix = `${Date.now()}-${Math.floor(Math.random() * 100000)}`;

  return {
    username: `perf_${suffix}`,
    email: TEST_USER_EMAIL,
    phoneNumber: randomPhone(),
    password: TEST_USER_PASSWORD,
    firstName: 'Performance',
    lastName: 'Tester',
    role,
  };
}

export function buildLoginPayload() {
  return {
    identifier: TEST_USER_IDENTIFIER,
    password: TEST_USER_PASSWORD,
  };
}

export function buildDeliveryPayload() {
  const suffix = `${__VU || 0}-${__ITER || 0}-${Date.now()}`;

  return {
    title: `Performance test delivery ${suffix}`,
    description: 'Generated by k6 performance tests',
    packageType: 'DOCUMENT',
    packageWeight: 1.5,
    packageDimensions: '30x20x5',
    isFragile: false,
    isUrgent: false,
    pickupAddress: 'Macedonia Square, Skopje',
    pickupLatitude: 41.99646,
    pickupLongitude: 21.43141,
    pickupContactName: 'Perf Pickup',
    pickupContactPhone: '+38970111222',
    pickupInstructions: 'Performance test pickup',
    dropoffAddress: 'City Park, Skopje',
    dropoffLatitude: 42.00698,
    dropoffLongitude: 21.41955,
    dropoffContactName: 'Perf Dropoff',
    dropoffContactPhone: '+38970333444',
    dropoffInstructions: 'Performance test dropoff',
    paymentProvider: 'CASH',
    promoCode: null,
    requestedPickupTime: null,
    requestedDeliveryTime: null,
  };
}

export function recordResponse(res, label) {
  apiLatency.add(res.timings.duration, { endpoint: label });
  apiErrors.add(res.status >= 400, { endpoint: label });
}

export function checkedRequest(method, path, body = null, token = null, expectedStatuses = [200]) {
  const url = `${BASE_URL}${path}`;
  const params = defaultHeaders(token);
  const payload = body === null ? null : JSON.stringify(body);

  let res;
  if (method === 'GET') {
    res = http.get(url, params);
  } else if (method === 'POST') {
    res = http.post(url, payload, params);
  } else if (method === 'PUT') {
    res = http.put(url, payload, params);
  } else if (method === 'PATCH') {
    res = http.patch(url, payload, params);
  } else if (method === 'DELETE') {
    res = http.del(url, payload, params);
  } else {
    throw new Error(`Unsupported method: ${method}`);
  }

  recordResponse(res, `${method} ${path}`);

  check(res, {
    [`${method} ${path} status is expected`]: (r) => expectedStatuses.includes(r.status),
    [`${method} ${path} response under 1500ms`]: (r) => r.timings.duration < 1500,
  });

  return res;
}

export function tryParseJson(res) {
  try {
    return res.json();
  } catch (_) {
    return null;
  }
}

export function extractAccessToken(authResponse) {
  const json = tryParseJson(authResponse);
  return json?.data?.accessToken || json?.accessToken || null;
}

export function registerUserIfNeeded(role = 'CLIENT') {
  if (!REGISTER_TEST_USER || !AUTH_ENABLED) {
    return;
  }

  const res = checkedRequest('POST', '/api/auth/register', buildRegisterPayload(role), null, [200, 201, 400, 409]);

  // 400/409 is acceptable when a stable TEST_USER_EMAIL already exists.
  check(res, {
    'register succeeded or user already exists': (r) => [200, 201, 400, 409].includes(r.status),
  });
}

export function login() {
  if (!AUTH_ENABLED) {
    return null;
  }

  const res = checkedRequest('POST', '/api/auth/login', buildLoginPayload(), null, [200]);
  const token = extractAccessToken(res);

  check(token, {
    'access token exists': (t) => !!t,
  });

  return token;
}

export function setupAuth(role = 'CLIENT') {
  registerUserIfNeeded(role);
  return login();
}

export function basicUserJourney(token) {
  checkedRequest('GET', '/actuator/health', null, null, [200]);
  checkedRequest('GET', '/api/auth/me', null, token, [200]);
  checkedRequest('GET', '/api/deliveries/mine', null, token, [200]);
  checkedRequest('POST', '/api/deliveries', buildDeliveryPayload(), token, [200, 201]);
  sleep(1);
}
